# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 134676fd1e79c614fe9600e98941839c8ddd5ff345af16eef4fd8d2f066f29963c22b7b5c2885c20a509e55e946db15b6eaebbf42cba4b1f207b67d09a39bc9d

test:
  secret_key_base: b96f5b7ffeaa1b0ee7e3571a2e7f2fb696d8193637293a39002cf482bd5da5099e132ed023528a1e71302175caae4fac2b16d58e1ec99152f00bd99600da30a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
